### ISSUE TITLE
Test loss is increasing?

### ISSUE THREAD

**Issue by EvanZ** [artem-oppermann/Deep-Autoencoders-For-Collaborative-Filtering#2]
I'm getting a weird behavior where training loss is decreasing and test loss is increasing. Any idea what might be happening?

```
epoch_nr: 0, train_loss: 1.323, test_loss: 0.964
epoch_nr: 1, train_loss: 0.990, test_loss: 0.960
epoch_nr: 2, train_loss: 0.988, test_loss: 0.964
epoch_nr: 3, train_loss: 0.990, test_loss: 0.963
epoch_nr: 4, train_loss: 0.986, test_loss: 0.965
epoch_nr: 5, train_loss: 0.974, test_loss: 0.968
epoch_nr: 6, train_loss: 0.963, test_loss: 0.975
epoch_nr: 7, train_loss: 0.951, test_loss: 0.985
epoch_nr: 8, train_loss: 0.942, test_loss: 0.996
epoch_nr: 9, train_loss: 0.930, test_loss: 0.997
epoch_nr: 10, train_loss: 0.926, test_loss: 0.999
epoch_nr: 11, train_loss: 0.921, test_loss: 1.004
epoch_nr: 12, train_loss: 0.920, test_loss: 1.005
epoch_nr: 13, train_loss: 0.919, test_loss: 1.007
.
.
.
epoch_nr: 265, train_loss: 0.589, test_loss: 1.291
epoch_nr: 266, train_loss: 0.589, test_loss: 1.292
epoch_nr: 267, train_loss: 0.588, test_loss: 1.293
epoch_nr: 268, train_loss: 0.588, test_loss: 1.293
epoch_nr: 269, train_loss: 0.588, test_loss: 1.292
epoch_nr: 270, train_loss: 0.586, test_loss: 1.294
epoch_nr: 271, train_loss: 0.586, test_loss: 1.294
epoch_nr: 272, train_loss: 0.585, test_loss: 1.293
epoch_nr: 273, train_loss: 0.586, test_loss: 1.293
epoch_nr: 274, train_loss: 0.585, test_loss: 1.294
epoch_nr: 275, train_loss: 0.585, test_loss: 1.294
epoch_nr: 276, train_loss: 0.586, test_loss: 1.297
```

**Comment by artem-oppermann** [comment]
Hello.
The training loss is also weird. In my opinion it is to small. Have you changed the loss function from the code in any way? How many ratings per user are you using in your testing set?

**Comment by EvanZ** [comment]
I didn't change anything in your code. Here is how I split the data:

```
    with open('ml-1m/ratings.dat', mode='r') as f:
        lines = f.readlines()
        train, test = train_test_split(lines, test_size=0.15)

```

**Comment by artem-oppermann** [comment]
Sorry for the late response.
You can not do it this way. You must take each user, take e.g 20 ratings of this user and put them into the test set and keep the rest as training set.

**Comment by EvanZ** [comment]
Hmmm....I don't see how that is different from what I did.

**Comment by artem-oppermann** [comment]
If  you do it your way, you can not guarantee that the training and test set have the same users.
Since during inference time you need a training sample from a user to make a prediction, you must have the same user in your test set to compare your made prediction with the ratings from the test set.

If your training set has 100 users, your test has must have the same 100 user.

**Comment by EvanZ** [comment]
Ok, just to be clear, let's say a user has 100 ratings. You would, say, put 80 of those in train and 20 in test. Train the autoencoder on the 80 ratings, and then the test loss would be predictions made with the model trained on 80 ratings against the 20 ratings in test?

**Comment by artem-oppermann** [comment]
Yes, you are right. And of course both sets have the same users. If you have the two datasets, you can use the preprocessing script on github two make the user-rating matrices for the both datasets. I think I made my split with this script:

`
ROOT_DIR='C:/Users/Admin/Desktop/deep_learning _local_datasets/colaborative filtering/ml-1m/ratings.dat'

OUTPUT_DIR_TRAIN='C:/Users/Admin/Desktop/deep_learning _local_datasets/colaborative filtering/ml-1m/train.dat'
OUTPUT_DIR_TEST='C:/Users/Admin/Desktop/deep_learning _local_datasets/colaborative filtering/ml-1m/test.dat'


NUM_USERS=6040
NUM_TEST_RATINGS=10


def _count_rating_per_user():
    
    rating_per_user={}
    user_counter=1
    rating_counter=0
    
    for line in open(ROOT_DIR):
        
        line=line.split('::')
        user_nr=int(line[0])
        
        if user_nr==user_counter:
            rating_counter+=1
        else:
            rating_per_user[user_counter]=rating_counter
            user_counter+=1      
            rating_counter=1

    return rating_per_user
            
                 
def _train_test_split():
    
    user_rating=_count_rating_per_user()
    temp_user=0
    test_counter=0
    
    train_writer=open(OUTPUT_DIR_TRAIN, 'w')
    test_writer=open(OUTPUT_DIR_TEST, 'w')
    
    for line in open(ROOT_DIR):
        
        splitted_line=line.split('::')
        user_nr=int(splitted_line[0])
        
        try:   
            if temp_user!=user_nr:
                write_test_samples=True
                temp_user=user_nr
                
            if user_rating[user_nr]<=NUM_TEST_RATINGS*2:
                continue
            else:
                
                if write_test_samples==True:
                    test_writer.write(line)
                    test_counter+=1
                    if test_counter>=NUM_TEST_RATINGS:
                        test_counter=0
                        write_test_samples=False        
                elif write_test_samples==False:
                    train_writer.write(line)
        
        except KeyError:   
            print('Key not found')
            continue
_train_test_split()          
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                `

**Comment by EvanZ** [comment]
Thanks! Makes sense now.

**Comment by artem-oppermann** [comment]
Okay, great. _:) Btw, What do you need that model for? Just for fun or educational purposes?

**Comment by EvanZ** [comment]
@artem-oppermann Trying to build an autoencoder for work to potentially replace an ALS-based recommendation engine. We don't actually care about the recommendations, however, just using the latent vectors for feature engineering.
