### ISSUE TITLE
record a website

### ISSUE THREAD

**Issue by ghost** [artem-oppermann/Deep-Autoencoders-For-Collaborative-Filtering#4]
This is tutorial about this code in Chinese. Copy it here in case forgetting the website.
https://mp.weixin.qq.com/s/mXJthyETebtww5TvEljuoQ

**Comment by artem-oppermann** [comment]
Okay, thanks for the info! :)

**Comment by wxs115** [comment]
what about train.dat and test.dat.how to use ratings.dat and movies.dat convert?
